### ISSUE TITLE
Docs: Funny apps

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1064]
# Tasks

- [ ] hollywood

brew tap real-aazam/homebrew-aazam
brew install hollywood

- [ ] [Cool-Retro-Term](https://github.com/Swordfish90/cool-retro-term/releases)
- [ ] Hacknet
- [ ] https://www.aura-office.co.jp/blog/omoshiro_web/
- [ ] brew install sl
- [ ] [unimatrix](https://github.com/will8211/unimatrix)

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
