### ISSUE TITLE
Fix build error for .prisma/client/index-browser

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1065]
# Tasks

Uncaught TypeError: Error resolving module specifier “.prisma/client/index-browser”. Relative module specifiers must start with “./”, “../” or “/”. 

- #607 実装時に発生した模様

- [x] 修正する

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
```
Removing the import of a Prisma enum type fixed the issue.

Somewhere in my code I had import an enum type. This seems to be apparently a Prisma problem.

So, remove any import { Enum } from '@prisma/client'; from your code.

See https://github.com/prisma/prisma/issues/12504
```
https://stackoverflow.com/questions/71601464/uncaught-typeerror-error-resolving-module-specifier-prisma-client-index-brow

**Comment by sinproject-iwasaki** [comment]
これで解決した。

https://github.com/prisma/prisma/issues/12504#issuecomment-1372632754

**Comment by sinproject-iwasaki** [comment]
こちらの方がシンプル

https://github.com/prisma/prisma/issues/12504#issuecomment-1285883083
