### ISSUE TITLE
CI: Build and run e2e test on release mode

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1068]
# Tasks

- [x] ビルドする
- [x] 4173 ポートで e2e テストを行う。
- [ ] テストを正常完了させる。

更新によりビルドが通らなくなることがあるので、CI にてビルドチェックを走らせてるのですが、

ビルドエラーは表示されない
ブラウザで表示させてみたら表示されない

という不具合がありました。
現在は e2e テストを 5173 ポートでやっているのですが、CIの場合はビルドして、3000 番ポートで確認するようにしたほうが良さそうです。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
- npm run preview では、WebSocket が使えずテストが通らない。
- npm run start では、https で接続できず、テストが通らない。

上記により、現時点では対応を保留とする。
