### ISSUE TITLE
Header: Fix active title Y-position on windows

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#1069]
# Tasks

- [ ] ヘッダーにボーダーが表示されているとき、テキスト部分が少し下にずれる問題の修正
　　※Windows環境でのみ発生

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by Acha0203** [comment]
Windows 環境で確認しましたが、ヘッダーには特に問題がないように見えます（Microsoft Edge および Google Chrome で確認）。

<img width="366" alt="talk_issue_1069" src="https://github.com/sinProject-Inc/talk/assets/74553433/54fe845a-0771-49a3-b495-c97b384ff5e6">

スクリーンショットの場合は「Learn」の下にボーダーが表示されていますが、テキスト部分（この場合は「Learn」）は下にずれていないように見えます。

それとも、何か他の問題があるのでしょうか？

なお、この Issue とは無関係ですが、Microsoft Edge で閲覧したところ、ヘッダーの左端のシンボルマークが表示されていませんでした（下のスクリーンショット参照）。すでに問題を把握されているかもしれませんが、念のためお伝えしました。

<img width="567" alt="talk_issue_1069-2" src="https://github.com/sinProject-Inc/talk/assets/74553433/d41a3941-e854-4137-b50b-aabd4e5b38b2">

**Comment by gottu91-code** [comment]
@Acha0203 

> Windows 10 環境で確認しましたが、ヘッダーには特に問題がないように見えます（Microsoft Edge および Google Chrome で確認）。

オフィスのwindowsで確認したところ、下にずれる現象を確認しました。
「Learn」「Translate」「Chat」を交互にクリックすると分かりやすいかと思います。

> Microsoft Edge で閲覧したところ、ヘッダーの左端のシンボルマークが表示されていませんでした

Microsoft Edge がavifに対応していないためです。以下に記載がございます。
- https://caniuse.com/avif

**Comment by gottu91-code** [comment]
@sinproject-iwasaki 

> Microsoft Edge がavifに対応していないためです。以下に記載がございます。
> https://caniuse.com/avif

上記、別 Issue にて対応が必要でしょうか？

**Comment by Acha0203** [comment]
@gottu91-code 

ご回答ありがとうございます。家族の PC（Windows 11）を使って確認したところ、下にずれる現象を確認できました。
また、Windows 10 環境の場合は、アイコンのみ下にずれていることがわかりました。テキストが下にずれるのは Windows 11 環境のみの現象のようです。

現在、下にずれる原因について調査しておりますので、判明し次第こちらの Issue に対応いたします。

**Comment by Acha0203** [comment]
@gottu91-code 

Windows 環境で調査した結果、修正できたのですが、あまりスマートな方法ではないのでご相談させてください。具体的には、tab.svelte の style を次のように変更することで修正できます：

```diff
<script lang="ts">
+	import { theme } from '$lib/stores'
+
	export let active = false
</script>

-<div class:active class="flex h-full items-center">
+<div class:active class="flex h-full items-center" class:dark={$theme === 'dark'}>
	<slot />
</div>

<style lang="postcss">
	.active {
- 		@apply border-b border-secondary pt-[1px] dark:border-secondary-dark;
+		border-bottom: 1px rgb(14, 165, 233) solid;
+		border-top: 1px rgba(0, 0, 0, 0) solid;
+	}
+
+	.dark {
+		border-bottom-color: rgb(56, 189, 248);
	}
</style>
```

この方法でよろしければ対応しますので、ご検討をお願いいたします。
