### ISSUE TITLE
Release v0.39.0

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1075]
# Tasks

## Tasks

- [x] package を書き換える

## GitHub

- [x] PR にラベルを付ける
- [x] リリースを作成する

## Server

- [x] cd ~/dev/talk
- [x] git checkout main
- [x] git pull
- [x] npm i
- [x] npm run build
- [x] pm2 restart talk

## Check

- [x] サーバーの表示確認を行う
- [x] SNS で告知する

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
