### ISSUE TITLE
Fix: links on App Structure

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1110]
# Tasks

- [x] Development を Dev Environment に書き換える
- [x] Dev Environment のリンク先を https://talk.sinpro.dev/docs/macos-settings に変更する
- [x] Our Concepts を Team sinProject に書き換える
- [x] Team sinProject のリンク先を https://talk.sinpro.dev/docs/our-team-policy に変更する
- [x] talk 3箇所を Learn に書き換える
- [x] talk 1箇所のリンク先 https://talk.sinpro.dev/ を https://talk.sinpro.dev/learn に変更する

500pt

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
