### ISSUE TITLE
Create mobile menu

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1113]
# Tasks

- [x] show 2nd line menu

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
![FyjA8waaYAIWcLc](https://github.com/sinProject-Inc/talk/assets/70736447/03fb4a0e-a4fd-4012-af4f-b2cb3c6e0c28)
