### ISSUE TITLE
Add background images

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1130]
# Tasks

- [x] Unsplashから画像を10枚取ってくる
- [x] 岩崎さんへ画像のURLをDM
- [x] OKのものをダウンロードする
- [x] AVIF30にする
- [x] 150kb以下にする
- [x] 画像を追加（自力で追加してみる）
- [x] 表示を確認する

1,500pt

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
