### ISSUE TITLE
Lighthouse: Serve static assets with an efficient cache policy 

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1144]
# Tasks

- [x] Lighthouse: Serve static assets with an efficient cache policy

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
https://github.com/sveltejs/kit/issues/3642#issuecomment-1031640046

**Comment by sinproject-iwasaki** [comment]
https://github.com/sveltejs/kit/issues/3194#issue-1092646279

**Comment by sinproject-iwasaki** [comment]
[How to set "Cache-Control" Header for static files in Caddy](https://fariszr.com/en/set-cache-header-caddy-files/)
