### ISSUE TITLE
Docs: Lighthouse and PageSpeed Insights

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1161]
# Tasks

https://www.google.com/search?q=PageSpeed+Insights+lighthouse+%E9%81%95%E3%81%84&rlz=1C5CHFA_enJP977JP977&oq=PageSpeed+Insights+lighthouse+%E9%81%95%E3%81%84&aqs=chrome..69i57.2908j0j4&sourceid=chrome&ie=UTF-8

- [ ] Docs: Lighthouse and PageSpeed Insights

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
