### ISSUE TITLE
Release v0.47.0

### ISSUE THREAD

**Issue by yoshimoto-takeshi** [sinProject-Inc/talk#1201]
# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Tasks

## Tasks

- [x] package のバージョンを 3 箇所書き換える。
- [x] push する。
- [x] PR を作成する。その際、Issue は Close しないので書き換えなくていい。
- [x] PR は、何もチェックせずにマージする。

## GitHub

- [x] Close されている PR で、機能拡張だと思われるものに Enhancement のラベルを付ける。
- [x] GitHub のリリース 作成ページを開き、あたらしいタグを作成する。
- [x] 自動生成されたリリースノートを Preview して問題がないかを確認する。
- [x] 問題なければ、リリースを作成する。

## Server

- [x] `ssh @dev@sinpro-dev` で接続する。
- [x] cd ~/dev/talk
- [x] git checkout main && git pull
- [x] npm i
- [x] npm run build
- [x] pm2 restart talk

## Check

- [x] サーバーの表示確認を行う

## 告知

- [x] ドキュメントの追加や更新があれば、 #give-and-take でアナウンスする。
- [x] SNS で告知するよう、プロダクトマネージャーに依頼する。

```markdown
@channel

Docs ガイドラインを更新しましたのでご案内いたします。
興味があるところ、業務に関係するところを確認しておいてくださいませ。

New

- Books

Update

- GitHub Actions - Secrets
- Git Branches and Commits - Script

確認が完了しましたらリアクションをお願い致します。
また、気になることがありましたらお気軽にご連絡くださいませ。
よろしくお願いいたします。

@岩崎 さん、SNS 告知お願い致します。
```
