### ISSUE TITLE
Docs: Remove sweets background image

### ISSUE THREAD

**Issue by yoshimoto-takeshi** [sinProject-Inc/talk#1209]
# Tasks

- [x] スイーツの背景画像を削除する
- [x] フォルダにある画像データも削除する（AVIF、jpegどちらも）
- [x] 追加する2枚の画像をAVIFに変換する
- [x] その画像を背景に追加する
- [x] ファイル名の「 _ 」を「 - 」に変更する

1000pt

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
