### ISSUE TITLE
Add products to Equipment and Supplies

### ISSUE THREAD

**Issue by yoshimoto-takeshi** [sinProject-Inc/talk#1239]
# Tasks

- [x] Equipment and Supplies に商品を追加する
- [x] 掃除機
- [x] 空気清浄機
- [x] オーブンレンジ
- [x] 各紹介リンクを指定のコードにする
- [x] 掃除機と空気清浄機のカテゴリー名を ChatGPT に聞いて作成する
- [x] 上記はカテゴリー Desk Furniture and Accessories の上に入れる
- [ ] v0.49.1 としてリリースする（ラベル不要）
- [ ] main にマージしてもらう
- [ ] リリースブランチやリリースイシューを作らずにリリースする

1000pt

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
