### ISSUE TITLE
Update to svelte4 and update npm packages

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1248]
# Tasks

- [x] Update packages

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
```
 talk git:(1248-update-packages) ✗ npm uninstall eslint-plugin-svelte3 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-svelte3@4.0.0
npm WARN Found: svelte@4.0.0
npm WARN node_modules/svelte
npm WARN   peer svelte@"^3.54.0 || ^4.0.0-next.0" from @sveltejs/kit@1.20.5
npm WARN   node_modules/@sveltejs/kit
npm WARN     peer @sveltejs/kit@"^1.0.0" from @sveltejs/adapter-node@1.2.4
npm WARN     node_modules/@sveltejs/adapter-node
npm WARN     1 more (the root project)
npm WARN   11 more (@sveltejs/vite-plugin-svelte, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer svelte@"^3.2.0" from eslint-plugin-svelte3@4.0.0
npm WARN node_modules/eslint-plugin-svelte3
npm WARN 
npm WARN Conflicting peer dependency: svelte@3.59.2
npm WARN node_modules/svelte
npm WARN   peer svelte@"^3.2.0" from eslint-plugin-svelte3@4.0.0
npm WARN   node_modules/eslint-plugin-svelte3
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: svelte-i18n@3.6.0
npm ERR! Found: svelte@4.0.0
npm ERR! node_modules/svelte
npm ERR!   peer svelte@"^3.54.0 || ^4.0.0-next.0" from @sveltejs/kit@1.20.5
npm ERR!   node_modules/@sveltejs/kit
npm ERR!     peer @sveltejs/kit@"^1.0.0" from @sveltejs/adapter-node@1.2.4
npm ERR!     node_modules/@sveltejs/adapter-node
npm ERR!       dev @sveltejs/adapter-node@"^1.2.4" from the root project
npm ERR!     dev @sveltejs/kit@"^1.20.5" from the root project
npm ERR!   peer svelte@"^3.54.0 || ^4.0.0-next.0" from @sveltejs/vite-plugin-svelte@2.4.1
npm ERR!   node_modules/@sveltejs/vite-plugin-svelte
npm ERR!     @sveltejs/vite-plugin-svelte@"^2.4.1" from @sveltejs/kit@1.20.5
npm ERR!     node_modules/@sveltejs/kit
npm ERR!       peer @sveltejs/kit@"^1.0.0" from @sveltejs/adapter-node@1.2.4
npm ERR!       node_modules/@sveltejs/adapter-node
npm ERR!         dev @sveltejs/adapter-node@"^1.2.4" from the root project
npm ERR!       1 more (the root project)
npm ERR!     peer @sveltejs/vite-plugin-svelte@"^2.2.0" from @sveltejs/vite-plugin-svelte-inspector@1.0.2
npm ERR!     node_modules/@sveltejs/vite-plugin-svelte-inspector
npm ERR!       @sveltejs/vite-plugin-svelte-inspector@"^1.0.2" from @sveltejs/vite-plugin-svelte@2.4.1
npm ERR!   10 more (@sveltejs/vite-plugin-svelte-inspector, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^3.25.1" from svelte-i18n@3.6.0
npm ERR! node_modules/svelte-i18n
npm ERR!   svelte-i18n@"^3.6.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: svelte@3.59.2
npm ERR! node_modules/svelte
npm ERR!   peer svelte@"^3.25.1" from svelte-i18n@3.6.0
npm ERR!   node_modules/svelte-i18n
npm ERR!     svelte-i18n@"^3.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/iwasakishinya/.npm/_logs/2023-06-28T02_57_43_688Z-eresolve-report.txt

```
