### ISSUE TITLE
Convert JPG/PNG files to AVIF

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1257]
# Tasks

- [x] Convert png files to avif files
- [x] Change refferences
- [x] Update 30-caddy.md
- [x] [squoosh.app/editor](https://squoosh.app/editor)
- [x] cavif で変換
- [x] Create a new doc page
- [x] コマンドラインツールの評価
- [x] Update patch version
- [x] Update a sitemap.xml file
- [x] Update a caddy configuration file
- [ ] Restart the server

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
