### ISSUE TITLE
Docs: Recruit

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1294]
# Tasks

- [ ] 挨拶
- [ ] 募集要項
- [ ] 手順
- [ ] 動画 YouTube（調査、質問、投稿方法、連絡）
- [ ] 質問調査、質問内容（やりたいこと、期待すること、得意なこと、苦手なこと、趣味, talk へのご意見、sinProject へのご意見、英語レベル）
- [ ] 履歴書、職務経歴書、Googleドライブ
- [ ] 可否連絡。

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
採用情報
https://docs.google.com/document/d/1B8smzn5WbJpkQp00ccVNFIZKlNzBJKKzomGI5g2uA-Y/edit

質問シート
https://docs.google.com/document/d/1XzxRPSy7sAE-C7D28sTMPYCfehSyPU_mZStrZIJsgYE/edit
