### ISSUE TITLE
Docs: Creating a Project with SvelteKit

### ISSUE THREAD

**Issue by yoshimoto-takeshi** [sinProject-Inc/talk#1297]
# Tasks

- [x] SvelteKit インストール手順を Docs に追加する
- [x] タイトルを追加する Creating a Project with SvelteKit
- [x] Doc の下に追加する
- [x] SSH Key Generation (https://talk.sinpro.dev/docs/ssh) を参考に書く
ターミナルに書く内容は $ をつける
返事の内容はそのまま書く

1000pt
7/3日中

npm create svelte@latest my-app

create-svelte version 5.0.2
┌  Welcome to SvelteKit!
│
◆  Which Svelte app template?
│  ○ SvelteKit demo app (A demo app showcasing some of the features of SvelteKit - play a word guessing game that works without JavaScript!)
│  ● Skeleton project
│  ○ Library project

◆  Add type checking with TypeScript?
│  ○ Yes, using JavaScript with JSDoc comments
│  ● Yes, using TypeScript syntax
│  ○ No

◆  Select additional options (use arrow keys/space bar)
│  ☑ Add ESLint for code linting
│  ☑ Add Prettier for code formatting
│  ☑ Add Playwright for browser testing
│  ☑ Add Vitest for unit testing

cd my-app

npm install

npm run dev

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
