### ISSUE TITLE
Docs: Add free image sites to Assets

### ISSUE THREAD

**Issue by yoshimoto-takeshi** [sinProject-Inc/talk#1299]
# Tasks

- [x] nixie tubeの缶が載っているところを検索して探す → いらすとや( https://www.irasutoya.com/ )
- [x] Assetsにフリー画像サイトを追加
- [x] 項目名 Illustration
- [x] フォントとSOUNDの間に入れる

500pt

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
