### ISSUE TITLE
Docs: Change the function example to a snaking case

### ISSUE THREAD

**Issue by yoshimoto-takeshi** [sinProject-Inc/talk#1319]
# Tasks

- [ ] Use early return pattern ( https://talk.sinpro.dev/docs/functions#use-early-return-pattern ) にある関数の例文を変更する
- [ ] isValid を snake_case の is_valid に変更する

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
