### ISSUE TITLE
Docs: Update style guide

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1333]
# Tasks

- [x] シングルクォート
- [x] セミコロン
- [x] 書籍

yusuke さん質問回答

普段はダブルクォーテーションやセミコロンを文末につけているのですが、コーディング規則ではつけないとなっていたので理由があれば教えていただきたいです。

[セミコロンに関する ESLint ルール](https://qiita.com/mysticatea/items/9da94240f29ea516ae87)

```
{
    "rules": {
        "semi": ["error", "never", {"beforeStatementContinuationChars": "never"}],
        "semi-spacing": ["error", {"after": true, "before": false}],
        "semi-style": ["error", "first"],
        "no-extra-semi": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "error"
    }
}
```

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
