### ISSUE TITLE
Change the Twitter Logo

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1355]
# Tasks
 
- [ ] Change the Twitter Logo
- [ ] Twitter場所 src/lib/components/twitter_link.svelte
- [ ] x_icon.svelte を作成する

```
<svg viewBox="0 0 24 24" aria-hidden="true" width="24" height="24" style="padding: 1px;"
	><g
		><path
			d="M14.258 10.152L23.176 0h-2.113l-7.747 8.813L7.133 0H0l9.352 13.328L0 23.973h2.113l8.176-9.309 6.531 9.309h7.133zm-2.895 3.293l-.949-1.328L2.875 1.56h3.246l6.086 8.523.945 1.328 7.91 11.078h-3.246zm0 0"
		/></g
	></svg
>
```
# Writing the Issue

1,000pt

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
