### ISSUE TITLE
Fix warnings on the portfolio page

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1359]
# Tasks

- [ ] Fix warnings on the portfolio page

```
+page.svelte:88 Unrecognized feature: 'web-share'.
h @ dom.js:1103
p @ dom.js:1123
update @ +page.svelte:88
update @ scheduler.js:119
flush @ scheduler.js:79
Promise.then (async)
schedule_update @ scheduler.js:20
make_dirty @ Component.js:81
(anonymous) @ Component.js:129
$$self.$$set @ root.svelte:54
(anonymous) @ proxy.js?v=09d9fc49:83
$set @ Component.js:483
dest.<computed> @ proxy.js?v=09d9fc49:46
navigate @ client.js?v=09d9fc49:1096
await in navigate (async)
(anonymous) @ client.js?v=09d9fc49:1567
Show 9 more frames
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.
10[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
```

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
