### ISSUE TITLE
Prevent errors from being displayed when opening the chat page without logging in

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1364]
# Tasks

- [ ] Prevent errors from being displayed when opening the chat page without logging in

insert line 6: `if (!locals.user) return`

Estimated Time: 3min

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by TeruyaYuma** [comment]
## 依頼内容の実施結果
(authed)/chat/[room_id]の+page.server.tsのline 6に` if (!locals.user) return`を設定した所(authed)/chat/[room_id]の+page.svelteにエラーが３箇所ほど出ました。

+page.svelte内のline 50の`export let data: PageData`にundefinedが入ってきている為、後続処理の型の整合性が合わずにエラーとなっています。
また、発生した対象エラー箇所を修正するだけでは無く全体的に型の整合性を合わせる為調整が必要かと思われます。

## 質問
このIssueの修正ですが、今回挙げられたタスクのみでは収まらないので別途相談させていただきたいと考えていますが宜しいでしょうか？
