### ISSUE TITLE
Change to svelte env access

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1367]
# Tasks

- [x] Change to svelte env access in translate_with_google_advanced.ts

Estimated Time: 10min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
こちらのタスクですが、$env/static/private を使用するように translate_with_google_advanced.ts のコードを変更する、という認識で合っていますでしょうか？

**Comment by sinproject-iwasaki** [comment]
@Acha0203 はい、その認識であっております。ご確認ありがとうございます！

**Comment by Acha0203** [comment]
- $env/static/private を使用するとユニットテストが通らないため、「import.meta.env.」を使って参照する方法に変更しました。
- マシンの性能の問題でe2eテストがタイムアウトしてしまうため、playwrite.config.tsのタイムアウト時間を変更しました。

**Comment by Acha0203** [comment]
[PR](https://github.com/sinProject-Inc/talk/pulls) を作成しましたが、GitHub Actions のテストでタイムアウトしてしまいます。timeout時間を5000くらいまで増やしても差し支えないでしょうか?

**Comment by gottu91-code** [comment]
@Acha0203 
`$env/static/private を使用するとユニットテストが通らないため、「import.meta.env.」を使って参照する方法に変更しました。`

**Comment by gottu91-code** [comment]
@Acha0203 
> $env/static/private を使用するとユニットテストが通らないため、「import.meta.env.」を使って参照する方法に変更しました。
ユニットテストは具体的にどのような形で通らないですか？ $env/static/privateを使って実装するというのが今回のタスク内容となりますので、詳細を教えてほしいです！

**Comment by Acha0203** [comment]
@gottu91-code 

エラーの内容は次のとおりです。

```
failed to load config from /Users/ikedaatsuko/web-projects/sinProject-Inc/talk/vite.config.ts

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '$env' imported from /Users/ikedaatsuko/web-projects/sinProject-Inc/talk/vite.config.ts.timestamp-1694199023628-ee9f9f86e3675.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

このエラーについてChatGPTに尋ねたところ、「import.meta.env.」を使って参照する方法を提示されました。試してみたところ、テストをパスしたので採用した次第です。
お手数おかけして申し訳ありません。よろしくお願いいたします。

**Comment by gottu91-code** [comment]
## 調査結果
「$env/static/private」や「$lib」は Sveltekit の機能。

- Sveltekitのコンテキスト (ルーティングロジック内) で「$env/static/private」や「$lib」が使える。

- vite.configでは「$env/static/private」や「$lib」が使えない。

### 備考
translate_with_google_advanced.ts で「$env/static/private」や「$lib」を使うと以下が発生する。
- ビルドエラー
- 開発サーバー起動エラー
- ユニットテストエラー

**Comment by sinproject-iwasaki** [comment]
@Acha0203 @gottu91-code 

ご対応ありがとうございます。こちらは一旦、今後対応方針を改めて決めたいと思いますので、終了したいと思います。
