### ISSUE TITLE
Update ESLint Settings

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/talk#1368]
# Tasks

- [x] ESLintの設定を更新する。
[ESLintページ](https://sinpro.dev/docs/eslint)を見て、sinpro-devと同じものを設定する。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by gottu91-code** [comment]
```
$ npm i eslint-plugin-prettier -D 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: talk@0.61.0
npm ERR! Found: prettier@2.8.8
npm ERR! node_modules/prettier
npm ERR!   dev prettier@"^2.8.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@">=3.0.0" from eslint-plugin-prettier@5.0.0
npm ERR! node_modules/eslint-plugin-prettier
npm ERR!   dev eslint-plugin-prettier@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/gotosho/.npm/_logs/2023-09-11T07_06_38_951Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/gotosho/.npm/_logs/2023-09-11T07_06_38_951Z-debug-0.log
```


```
Oops! Something went wrong! :(

ESLint: 8.43.0

TypeError: prettier.resolveConfig is not a function
    at /Users/gotosho/development/talk/node_modules/eslint-plugin-prettier/worker.js:38:24
```
