### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1376]
# Tasks

- [x] Update npm packages
- [x] npm run dev で表示を確認し、エラーが出ないこと
- [x] npm run build && node build で表示を確認し、エラーが出ないこと

```bash
cd <project_root>
ncu
ncu -u
npm i
```

pritter 3 への更新の際に微調整が必要です。[こちら](https://github.com/sinProject-Inc/sinpro-dev/pull/130/files)を参考にしてください。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by akamini** [comment]
三つ目のタスク「npm run build && node build で表示を確認し、エラーが出ないこと」にあるnode buildはnpm run buildと同じスクリプトコマンドで書かれているように実行することでビルドされるという認識でよろしいでしょうか？

**Comment by sinproject-iwasaki** [comment]
@akamini 

ご質問ありがとうございます。

> node buildはnpm run buildと同じスクリプトコマンドで書かれている

ここの質問がよくわからないのですが、mpn run build と node build は別のコマンドです。この2つのコマンドを実行してくださいという依頼になります。

**Comment by akamini** [comment]
nodeをビルドしたことがなかったので、node buildというコマンドを実行できることを知りませんでした。
ご回答ありがとうございます。

**Comment by akamini** [comment]
@sinproject-iwasaki 
2点、確認したい点がございます。
1. ncuで確認したところ、**pritter 3**の更新がありませんでしたが、進めて問題ないでしょうか？
2. npm run build && node buildコマンドを実行した際、下記のエラーが発生しました。Intlなどを別途インストールして対応した方がよろしいでしょうか？

npm run build && node build

> talk@0.61.0 build
> vite build


vite v4.4.9 building SSR bundle for production...
✓ 327 modules transformed.

node:internal/event_target:1006
  process.nextTick(() => { throw err; });
                           ^
file:///Users/xxx/xxx/talk/.svelte-kit/output/server/chunks/runtime.esm.js:3
import { IntlMessageFormat } from "intl-messageformat";
         ^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'IntlMessageFormat' not found. The requested module 'intl-messageformat' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'intl-messageformat';
const { IntlMessageFormat } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async analyse (file:///Users/xxx/xxx/talk/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:60:16)
    at async MessagePort.<anonymous> (file:///Users/xxx/xxx/talk/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.12.1

**Comment by sinproject-iwasaki** [comment]
@akamini 

> 1. ncuで確認したところ、**pritter 3**の更新がありませんでしたが、進めて問題ないでしょうか？

はい、Prettier は他の対応ですでに更新してしまいましたので問題ありません。

> 2. npm run build && node buildコマンドを実行した際、下記のエラーが発生しました。Intlなどを別途インストールして対応した方がよろしいでしょうか？
> 
> npm run build && node build

こちらの環境いま試してみたところ、エラーを発生させられませんでした。

```
$ npm run build
$ node build
```

の2つのコマンドに分けて実行してみて、どちらでエラーが発生しているかを確認すると良いと思います。
推測すると `npm run build` でコケていると思いますが、

- 事前に `npm i` は実行済みでしょうか？
- また、このエラーは、ネットやChatGPTで調査済みでしょうか？
- こちらの環境の node は 18.16.0 でした。node バージョンが古い場合もこのエラーが発生するかもしれませんので、バージョンが違う場合は更新してみてください。

原因が判明したら、この Issue に記載した後、ご連絡いただけましたら幸いです。

**Comment by akamini** [comment]
nodeやグローバルパッケージも最新だったため、package-lock.jsonの削除やnpmのキャッシュクリアなど様々な方法をためしましたが、結果として下記をインストールすることでビルドが通り、`npm run build && node build`を実行できるようになりました。

`npm install intl-messageformat@latest
`

**Comment by akamini** [comment]
コミットをプッシュする際に以下のようなエラーが発生しました。

```
/Users/yusuke.a/workspace/talk/src/lib/components/social_meta_tags.svelte:29:3
Error: Type '{ url: string; type: string; title: string; description: string; images: { url: string; alt: string; }[]; site_name: string; }' is not assignable to type 'OpenGraph'.
  Object literal may only specify known properties, but 'site_name' does not exist in type 'OpenGraph'. Did you mean to write 'siteName'? (ts)
                images: [{ url: image_url, alt: image_alt }],
                site_name,
        }}


====================================
svelte-check found 1 error and 0 warnings in 1 file
husky - pre-push hook exited with code 1 (error)
error: failed to push some refs to 'https://github.com/sinProject-Inc/talk.git'
```
OpenGraphの型エラーだったので、types.d.tsファイルの型をsiteNameからsite_nameに修正することでプッシュできました。

**Comment by sinproject-iwasaki** [comment]
> ```
> /Users/yusuke.a/workspace/talk/src/lib/components/social_meta_tags.svelte:29:3
> Error: Type '{ url: string; type: string; title: string; description: string; images: { url: string; alt: string; }[]; site_name: string; }' is not assignable to type 'OpenGraph'.
>   Object literal may only specify known properties, but 'site_name' does not exist in type 'OpenGraph'. Did you mean to write 'siteName'? (ts)
>                 images: [{ url: image_url, alt: image_alt }],
>                 site_name,
>         }}
> ====================================
> ```
> OpenGraphの型エラーだったので、types.d.tsファイルの型をsiteNameからsite_nameに修正することでプッシュできました。

こちらは、package の更新による影響です。

types.d.ts の変更を元に戻し、上記メッセージと確認し、[こちら](https://github.com/sinProject-Inc/sinpro-dev/pull/255/files#diff-a8f8102e2f9ecab89c46615a359e1837d9fbd4f4738c4086c3cc504104173dbb)と同じ対応を行ってくださいませ。

**Comment by akamini** [comment]
ご確認ありがとうございます。
sinpro-devのIssueを参考にsocial_meta_tags.sveltファイルを修正し、再プッシュいたしました。

**Comment by gottu91-code** [comment]
@akamini 

- [ ] CI が すべて pass することを確認し、PRの `Make sure CI completes successfully`  にチェックを入れる。
