### ISSUE TITLE
Modify the Creating a Project link

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#1387]
# Tasks

- [x] change to `https://sinpro.dev/docs/creating-a-project`

target: readme.md

Estimated Time: 2min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
`npm install` を実行すると critical なエラーが検出されました。npm audit report に書かれているとおり `npm audit fix` または `npm audit fix --force` で修正するべきでしょうか？`

```
# npm audit report

postcss  <=7.0.35
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-hwj9-h5mp-3pm3
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
No fix available
node_modules/@fullhuman/postcss-purgecss/node_modules/postcss
node_modules/postcss-functions/node_modules/postcss
node_modules/purgecss/node_modules/postcss
  @fullhuman/postcss-purgecss  2.0.3 - 3.0.0
  Depends on vulnerable versions of postcss
  Depends on vulnerable versions of purgecss
  node_modules/@fullhuman/postcss-purgecss
    tailwindcss  0.1.0 - 2.2.0-canary.16
    Depends on vulnerable versions of @fullhuman/postcss-purgecss
    Depends on vulnerable versions of postcss-functions
    node_modules/tailwindcss-dir/node_modules/tailwindcss
      tailwindcss-dir  *
      Depends on vulnerable versions of tailwindcss
      node_modules/tailwindcss-dir
  postcss-functions  <=3.0.0
  Depends on vulnerable versions of postcss
  node_modules/postcss-functions
  purgecss  <=1.0.1 || 2.0.1-beta.0 - 3.0.0
  Depends on vulnerable versions of postcss
  node_modules/purgecss

protobufjs  7.0.0 - 7.2.3
Severity: critical
protobufjs Prototype Pollution vulnerability - https://github.com/advisories/GHSA-h755-8qp9-cq85
fix available via `npm audit fix`
node_modules/protobufjs
  google-gax  2.2.1-pre - 2.2.1-pre.2 || 2.28.2-alpha.1 - 2.28.4-alpha.1 || 3.1.4 - 3.6.0 || 4.0.0
  Depends on vulnerable versions of protobufjs
  node_modules/google-gax

semver  <5.7.2 || >=6.0.0 <6.3.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install imap-simple@1.6.3, which is a breaking change
node_modules/imap/node_modules/semver
node_modules/make-dir/node_modules/semver
  utf7  >=1.0.2
  Depends on vulnerable versions of semver
  node_modules/imap/node_modules/utf7
    imap  >=0.8.18
    Depends on vulnerable versions of utf7
    node_modules/imap
      imap-simple  >=2.0.0
      Depends on vulnerable versions of imap
      node_modules/imap-simple

word-wrap  <1.2.4
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
fix available via `npm audit fix`
node_modules/word-wrap

13 vulnerabilities (11 moderate, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.
```

**Comment by iamsin** [comment]
> `npm install` を実行すると critical な脆弱性が検出されました。npm audit report に書かれているとおり `npm audit fix` または `npm audit fix --force` で修正するべきでしょうか？

`npm i --legacy-peer-deps`

をお試しください。状況変わらなくても、近日

- #1376 

で対応予定ですので、そのままで結構です。

作業に問題が出るようでしたらまたご連絡くださいませ。

**Comment by Acha0203** [comment]
ご回答ありがとうございます。

大変申し訳ありませんが質問の内容に一部誤りがありました。正しくは `npm install` ではなく `npm i --legacy-peer-deps` の方です。

従いまして、状況は変わっておりませんが、ご指示の通りそのままにしておきます。
