### ISSUE TITLE
Update PR template

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/talk#1391]
# Tasks

file: pull_request_template.md

- [x] Add the following at the beginning of 'Tasks'
```
Make sure all checkboxes in the Issue content are checked
Make sure the PR title is in the format <Issue Title> <Issue Number>
```

Estimated Time: 5min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
