### ISSUE TITLE
Update .eslintrc.cjs

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/talk#1396]
# Tasks

- [x] [sinpro-dev Update .eslintrc.cjs](https://github.com/sinProject-Inc/sinpro-dev/issues/275) と同じ対応をする

※実際の対応は、sinpro-dev の最新の .eslintrc.cjs の内容をコピーして貼り付け。その後、フォーマットを行い、軽く動作を確認する。

Estimated Time: 10min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
[Update .eslintrc.cjs #275](https://github.com/sinProject-Inc/sinpro-dev/issues/275) の「空行を入れる定義をまとめる」の意味がよくわからないのですが、具体的には.eslintrc.cjs の内容を [Update .eslintrc.cjs #275 #276](https://github.com/sinProject-Inc/sinpro-dev/pull/276/files) と同じにする、という理解で合っていますでしょうか？

**Comment by gottu91-code** [comment]
> Update .eslintrc.cjs #275 の「空行を入れる定義をまとめる」の意味がよくわからないのですが、具体的には.eslintrc.cjs の内容を Update .eslintrc.cjs #275 #276 と同じにする、という理解で合っていますでしょうか？
その理解で合っております！
