### ISSUE TITLE
Add npm run branch script

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/talk#1399]
# Tasks

- [ ] Add [the create_git_branch.ts from sinpro-dev](https://github.com/sinProject-Inc/sinpro-dev/blob/main/src/lib/git/create_git_branch.ts).
- [ ] Add the following to the scripts section of package.json.
`"branch": "git checkout main && git pull && tsx ./src/lib/git/create_git_branch.ts"`

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by gottu91-code** [comment]
こちら未対応と勘違いしIssueを作成してしまいました。すでに対応済みとなります。Closeいたします。
