### ISSUE TITLE
Do not use Record

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/talk#1413]
# Tasks

- [ ] Complete the following TODO
```
Todo name: Do not use Record
file: src/lib/api/api_path.ts
target function: connect_with_params
```

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
