### ISSUE TITLE
Search for the selected text, etc

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/talk#1431]
# Tasks

- [ ] Complete the following TODO
```
Todo name: 選択されているテキストを探す
Todo name: 翻訳を登録する
Todo name: 選択されているテキストと翻訳を関連付ける
file: /src/routes/(authed)/learn/+page.svelte
target: add_translation関数のawait show_translation()処理の後
```

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
