### ISSUE TITLE
Start an HTTPS server with 'npm run dev'

### ISSUE THREAD

**Issue by iamsin** [sinProject-Inc/talk#1440]
# Tasks

- [ ] `npm i vite-plugin-mkcert -D`
- [ ] Update a vite.config.ts
- [ ] connect https://192.168.XXX.XXX:5173

Estimated Time: 60min

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
