### ISSUE TITLE
Set tsconfig to strictest

### ISSUE THREAD

**Issue by REI-MORI** [sinProject-Inc/talk#1445]
# Tasks

- [x] Configure tsconfig.json

Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by REI-MORI** [comment]
@sinproject-iwasaki  2点確認させていただきたいことがございます。

## テストコードにハードコーディングしているIPアドレス

テストでexpectedの値としてIPアドレスをテストコード内にハードコーディングしています。sonarcluodでセキュリティに問題があるという指摘がありましたが、ステータスをsafeとしてもよろしいでしょうか。

![image](https://github.com/sinProject-Inc/talk/assets/93172801/140262a6-10e8-4734-b68e-0ba62e4e5b65)

## 各テストコードの重複

CODE CLIMATEで各テストコードで似たようなコードがあるという指摘がありました。これは必要だと思いますのでそのままでよろしいでしょうか。

![image](https://github.com/sinProject-Inc/talk/assets/93172801/c373436a-5f00-4428-bdec-b1ecece44e96)

**Comment by sinproject-iwasaki** [comment]
> テストでexpectedの値としてIPアドレスをテストコード内にハードコーディングしています。sonarcluodでセキュリティに問題があるという指摘がありましたが、ステータスをsafeとしてもよろしいでしょうか。

テストコードでのセキュリティ警告は、すべて safe で大丈夫です。

> CODE CLIMATEで各テストコードで似たようなコードがあるという指摘がありました。これは必要だと思いますのでそのままでよろしいでしょうか。

CODE CLIMATE は一旦放置しましょう。今後対応を検討します。
