### ISSUE TITLE
Configure Playwright

### ISSUE THREAD

**Issue by REI-MORI** [sinProject-Inc/talk#1451]
# Tasks

- [ ] Configure Playwright

Estimated Time: XXmin

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by REI-MORI** [comment]
@sinproject-iwasaki この対応は以下の認識で合っていますでしょうか。

- 以前に書かれたテストがコメントアウトされています。これを有効化してe2eディレクトリ配下のテストを通るようにする
- playwright/.auth/user.jsonにテストで使用するユーザー情報を設定する。ファイルは存在しないので新規作成

**Comment by sinproject-iwasaki** [comment]
@REI-MORI 

> この対応は以下の認識で合っていますでしょうか。

違います。https://github.com/sinProject-Inc/sinpro-template-for-sveltekit/issues/35 の Issue での対応と、sinpro.dev を参考に playwright.config を刷新してください。よろしくお願いいたします。

基本的には、共通化はすべて sinpro-template-for-sveltekit の対応内容と sinpro.dev の対応内容、および https://sinpro.dev を参考にしてください。
また、岩崎へ質問を送る前に、他のプロジェクトで対応している方がいれば相談するようにしてみてくださいませ。

**Comment by REI-MORI** [comment]
@sinproject-iwasaki 
playwright.config.tsのtestDirについて質問です。
池田さんに確認していただいたところ、testDirの設定値を'e2e'にした方が良いとのことだったのですが、e2eにするとCIでエラーとなってしまいます。

```
> talk@0.61.0 test:e2e
> playwright test

[WebServer] 

Running 37 tests using 2 workers
T

  1) [setup] › auth.setup.ts:38:1 › sign in ────────────────────────────────────────────────────────

    Test timeout of 30000ms exceeded.

    Error: locator.fill: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for getByPlaceholder('Enter email')
      -   locator resolved to <input required="" type="email" name="email" class="inp…/>
      - elementHandle.fill("")
      -   waiting for element to be visible, enabled and editable
      -     element is not visible - waiting...


      45 | 	// expect(gmail_user).toEqual('***')
      46 |
    > 47 | 	await page.getByPlaceholder('Enter email').fill(gmail_user)
         | 	                                           ^
      48 | 	await page.getByRole('button', *** name: 'Continue' ***).click()
      49 | 	await page.waitForURL(/\/pin-code/)
      50 | 	await page.waitForLoadState('networkidle')

        at /home/runner/work/talk/talk/e2e/auth.setup.ts:47:45

    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results/auth.setup.ts-sign-in-setup/video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

  Slow test file: [setup] › auth.setup.ts ([30](https://github.com/sinProject-Inc/talk/actions/runs/6978025239/job/18993237575#step:13:31).0s)
  Consider splitting slow test files to speed up parallel execution
  1 failed
    [setup] › auth.setup.ts:38:1 › sign in ─────────────────────────────────────────────────────────
  [36](https://github.com/sinProject-Inc/talk/actions/runs/6978025239/job/18993237575#step:13:37) did not run
Error: Process completed with exit code 1.
```

こちらはどのように対応すればよろしいでしょうか。
(1) テストコードを修正してe2eディレクトリにあるテストを実行する
(2) 一旦、他のリポジトリと同じようにtestDirにtestsを設定する

**Comment by sinproject-iwasaki** [comment]
@REI-MORI @Acha0203 

他の理事とリトを見ていただくとわかるかと思いますが、E2E テストはすべて tests フォルダに変更されています。よって、こちらも E2E のフォルダは tests にしてください。

**Comment by Acha0203** [comment]
@sinproject-iwasaki 

現在の「e2e」フォルダの名称を「tests」に変更するという認識で合っていますでしょうか？

**Comment by sinproject-iwasaki** [comment]
@Acha0203 

はい、あっております！
