### ISSUE TITLE
Activate SonarCloud coverage

### ISSUE THREAD

**Issue by REI-MORI** [sinProject-Inc/talk#1452]
# Tasks

- [x] [こちら](https://github.com/sinProject-Inc/sinpro-dev/pull/328/files)と同じ対応をする
 
Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by REI-MORI** [comment]
@sinproject-iwasaki 
以下2点お願いいたします。いずれも権限がないため操作できませんでした。

- sonarcloudのAutomatic AnalysisをOFF
- このリポジトリでSONAR_TOKENを登録

お手数をおかけいたしますがよろしくお願いいたします。

**Comment by sinproject-iwasaki** [comment]
@REI-MORI 

> sonarcloudのAutomatic AnalysisをOFF

OFF にしました。

> このリポジトリでSONAR_TOKENを登録

キー名を SONARCLOUD_TOKEN として登録しました。
