### ISSUE TITLE
Setup ecosystem file for PM2

### ISSUE THREAD

**Issue by REI-MORI** [sinProject-Inc/talk#1454]
# Tasks

- [x] [こちら](https://github.com/sinProject-Inc/sinpro-template-for-sveltekit/pull/54/files)と同じ対応をする

Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
