### ISSUE TITLE
Configure SonarCloud Test Coverage - Part2(#1459)

### ISSUE THREAD

**Issue by REI-MORI** [sinProject-Inc/talk#1463]
# Tasks

- [x] Edit .github/workflows/ci.yml
- [x] Change path of create_git_branch.ts 

Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
