### ISSUE TITLE
Use it.each on Vitest test codes

### ISSUE THREAD

**Issue by REI-MORI** [sinProject-Inc/talk#1466]
# Tasks

- [ ] Pelace "test.each" to "it.each" on test pages  

Estimated Time: XXmin

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
