### ISSUE TITLE
Change html format to Prettier

### ISSUE THREAD

**Issue by Acha0203** [sinProject-Inc/talk#1471]
# Tasks

- [x] `npm audit fix` を実行して package のバージョンを調整する
- [x] html のフォーマットを Prettier に変更する

Estimated Time: 15min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
