### ISSUE TITLE
Chat by room

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#448]
# Tasks

- [x] Add a button for creating a new room
- [x] Clicking it makes a new room with an ID
- [x] the URL will become https://...../chat/(id)
- [x] Having another person open that URL will prompt them with a username and they can enter that room

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
