### ISSUE TITLE
Save front log on server disconnected

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#502]
# Tasks

- [x] When server is not on, store client messages in localstorage
- [x] When a message has been sent, send all messages from localstorage

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
