### ISSUE TITLE
Support profile icon

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#536]
# Notes
- .envを更新してください
- データーベースをリセットしてください
```
npx prisma db push
npx prisma generate
npx prisma db seed
npx prisma migrate reset
```

# Tasks

- [x] Profile screen with changeable icon only
- [x] Icon - ~~PNG~~, JPG, 5MB
- [x] Show icon on the left of name in chat
- [x] Dummy icon
- [x] Header button

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
