### ISSUE TITLE
Create doc pages

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#580]
# 目的

- Document for talk
- Document for team
- sinProject WebSite

# Tasks

- [x] md ファイルを読み込んで表示する。
- [x] md ファイルのメタ情報を取得する。
- [x] 基本的な体裁を整える。
- [x] カテゴリー名を表示する。
- [x] リンクは新しいタブで開く。
- [x] 左メニューを準備する。
- [x] プリレンダリングする。
- [x] /docs にアクセスが有った場合はリダイレクトする。
- [x] ページ内メニューを表示する。
- [x] ドキュメント編集リンクを付ける。
- [x] アクティブなページのメニューの色を変える。
- [x] メニューを tailwind スタイルにする。
- [x] 文字のカラーを tailwind スタイルにする。
- [x] リンクを tailwind スタイルにする。
- [x] コンテンツ部分だけスクロールする。
- [x] スクロールバーを右端に表示する。
- [x] ドキュメントナビゲーターをつける。
- [x] ページ内のメニューを表示する。
- [x] 幅によりメニューを折りたたむ。
- [x] 画面を中央に寄せる。
- [x] スクロールが行き過ぎたときの背景色を暗くする。

# Header

- [x] ヘッダーを付ける。
- [x] 半透明にする。
- [x] メニューを表示する。
- [x] アイコンを変更する。
- [x] h2 リンクのスクロールに対応する。

# Page Sections

- [x] サーバーからデータを取得して列挙する。
- [x] リンクを貼る。
- [x] ページURLの場合は先頭に戻る。
- [x] 右に表示する。
- [x] スクロールしない。
- [x] アクティブ時に色を変える。
- [x] ホバー時に色を変える。
- [x] セクションホバー時にリンクアイコンを表示する。
- [x] 部分スクロールできるようにする。

**Comment by sinproject-iwasaki** [comment]
[Install Tailwind CSS with SvelteKit](https://tailwindcss.com/docs/guides/sveltekit)

**Comment by sinproject-iwasaki** [comment]
[フロントエンド完結の検索エンジン完全に理解した](https://qiita.com/Sashimimochi/items/4972b3dc333c6e5fb866)
日本語対応サンプル。
