### ISSUE TITLE
Change design to be more like the tailwind documentation design

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#582]
# Tasks

- [x] 入力欄の色が見えづらい #607 にて対応
- [x] add borders on glass panels?  #969 にて対応
- [x] glass panels transparency  #607 にて対応
- [x] make background darker (dark:bg-primary-dark-8/[0.54]とbg-primary-8/[0.54])
- [x] make code blocks use the glass panel

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
