### ISSUE TITLE
Decrease glass transparency

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#594]
# Tasks

- [x] ガラスの透明度を下げる

5/25 19:30追記
以下の内容を、docsページのコードブロックと同様にする
- [x] 背景カラー
- [x] 透明度
- [x] ボーダーライン

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
