### ISSUE TITLE
Docs: Theme

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#607]
# Tasks
- [x] テーマに対応し配色設定を行う。
- [x] ダークモード、ライトモードの切り替えを実装する（Tailwindの「システム」は不要）
- [x] 初期状態は、システム設定のカラーを反映する。
# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
