### ISSUE TITLE
Docs: Add page transitions

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#662]
# Tasks

- [x] Docs内でのページ遷移時のtransitionを実装

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sakata0411** [comment]
- [ ] transitionの処理中、OnThisPage.svelteの要素の表示位置がずれる問題の修正
