### ISSUE TITLE
Docs: Add shortcut keys for search box

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#689]
# Tasks

- [x] "Opt+K" or "Ctrl + K" で検索ウィンドウが開くようにする
- ~~[ ] Docs画面左上の検索ボックスに上記ショートカットキーの表示を追加する~~

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
