### ISSUE TITLE
Docs: Setting sidebar for search box

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#690]
# Tasks

- [x] Docs画面左上の検索ボックスはSidebarの上限スクロールに対応しないように変更する。(画面上部に固定されるようにする)
- [x] Sidebarの内容がスクロールされた際の挙動に、検索ボックスの下に入り込むような影の表現をつける。
（参考：Tailwindサイト）

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
