### ISSUE TITLE
Docs: Change design of search result window

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#691]
# Tasks
検索用ウィンドウの見た目の調整
- [x] 検索ワード入力欄のフォントサイズを下げる
- [x] 検索結果が0件だったときの表示を「No results for “XXX」に変更
- [x] 検索結果リストの上下paddingを左右と揃える

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
