### ISSUE TITLE
Docs: Show H2 headings in search

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#693]
# Tasks

- [x] ページ内の h2 のリンクを結果一覧として表示する。

(参考：fuse.js の公式サイト)
※fuse.js 公式サイトがどのような index を作っているか確認する必要がありそう?

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
