### ISSUE TITLE
Docs: Show previous search result

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#695]
# Tasks

- [x] 検索用ウィンドウに文字を入力した状態でウィンドウを閉じた場合、開きなおしても入力内容が残るようにする
- [x] ページ移動を挟んだ場合も残るようにする。(リロードでは残っても残らなくても良い)

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
