### ISSUE TITLE
Docs: Search by selected words when opened

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#696]
# Tasks

- [x] 範囲選択された状態で検索ウインドウが開かれたとき、範囲選択された文字列で初期検索を行う
（参考：Tailwind サイト）

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
