### ISSUE TITLE
Correct English in the templates

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#705]
# Tasks

- [x] Correct English in the Issue template
- [x] Correct English in the PR template

# Write an issue

- [x] Write each checklist item of this issue in tasks, one by one
- [x] Write all verbal instructions in tasks

# Before starting an issue

- [x] Share screen on Discord
- [x] Send a start notification on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the Issue

# Pre-PR Check

- [x] Changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
