### ISSUE TITLE
Correct the English of the custom issue template

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#706]
# Tasks

- [ ] Correct the English of the custom issue template

# Writing the issue

- [ ] Write each task of this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before starting working on the issue

- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the Issue

# Pre-PR Check

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
