### ISSUE TITLE
Update PR template

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#708]
# Tasks

- [x] Add "close #issune_number" line
- [x] Add "Add reviewers" line
- [x] Fix: use default template for PR

# Writing the issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before starting working on the issue

- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Check

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
