### ISSUE TITLE
Update issues with issue template

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#711]
# Tasks

- [x] 先週作ってマイルストーンに入れたイシューをイシューテンプレで書き直す
（New issue→Custom issue templateを押すとテンプレが出ます）

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by milkyskies** [comment]
Completed
