### ISSUE TITLE
Docs: Change to GitHub icon from link text

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#714]
# Tasks

- [x] Change to GitHub icon from link text ("on Github"→GitHubアイコンを表示するようにする)
DocsのCreating a Projectにある「ー」を参考に同様の実装をする。
- [x] Add arrow

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sakata0411** [comment]
@sinproject-iwasaki 対応内容について質問です。

このissueについて、mdファイルの中身を編集する(「on GitHub」になっている部分に直接idを指定する等)形での実装しか対応方法が思いつかない状況にあります。
おそらくそれは求められている実装とは違うと考えていますので、どういった実装方法が考えられるか教えていただきたいです。
(特定の文字列を検知した際に処理をする方法、で考えており、この「特定の文字列を検知」をどうすればよいか見当がついていない状態です。)

(教えていただいた内容で#702:Replace link arrow も対応する予定です。)
