### ISSUE TITLE
Update PR template

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#718]
# Tasks

- [x] 「PR 完了コメントを記載する」を追記
- [x] 「マージ担当者に連絡する」を追記

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
