### ISSUE TITLE
Docs: Refactor function set_scroll_result 

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#726]
# Tasks
対象：src/routes/docs/search-modale.svelte
- [x] 何を計算しているのか分かりにくくなっているため、処理ごとにfunctionを作成し可読性を上げる

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
