### ISSUE TITLE
Docs: Fix 404 error by search button on header

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#729]
# Tasks
以下の指摘点について、現状の確認および修正を実施
- [ ] 画面が広いときも検索ボタンがヘッダーに表示されている
- [ ] ヘッダーの検索ボタンをタップすると404エラーになる

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
