### ISSUE TITLE
Docs: Fix behavior when entering TAB key on search window

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#736]
# Tasks
検索ウィンドウが表示されているときのTABキーによるカーソル移動の処理を実装する
- [x] TABキーによるカーソル移動でも検索結果の選択(active化)が行われるようにする(現状は両者が個別に動いている)
- [x] TABキーによるカーソル移動の対象が検索ウィンドウの外に行かないようにする

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
