### ISSUE TITLE
Docs: Fix shadow of sidebar sections

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#738]
# Tasks
section一覧と検索ボタンが重なる際に表示する影についての改善
- [x] もう少し影をはっきりと
- [ ] 通常時は影が表示されないようにする
 tailwindを参考にすすめる。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by sakata0411** [comment]
対応内容についてですが、参考としているtailwindのページは「背景が単色」という前提で作られていたため、talkには同じ方法が使えませんでした。
また、javascriptでの制御で近しいことは可能になるかとは思いますが、実装がかなり手間になりそうであったため、ひとまず以下の変更をしました。

- 検索ボックスのshadowに加え、半透明のグラデーションの要素を配置しより影らしくなるように(tailwindのサイトを参考)

- 上記実装をするため、およびスクロールバーの表示位置を変えるためにside-bar、+layoutの調整
