### ISSUE TITLE
Docs: Git Config User Profiles

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#762]
# Tasks

- [x] 下記の内容のdocを書く
【VScord GitHubアカウント設定(共用端末向け)】
[1]extensionsタブから「Git Config User Profiles」をInstall
[2]コマンドパレット(Shift + Command + P)にて「git config user profiles : create a git config user profile」を検索・実行
	以降、順に「プロフィール名(任意の値)」「アカウント名(任意の値)」「GitHubメールアドレス」を入力していきプロフィールを作成。
[3]コマンドパレットにて「「git config user profiles : select a git config user profile」を検索・実行
	右下に確認のポップアップが表示されるので問題なければそのまま実行。
	※この操作で、開いているファイル内に記載されているアカウント情報が更新されます。
※選択中のプロフィールと、開いているファイルとの間にアカウント情報に相違がある場合、画面下部の青いバーの部分に黄色で警告表示が出ます。
	その場合はそこをクリックするか、上記[3]の検索をかけて対応してください。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
