### ISSUE TITLE
Docs: Slack

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#774]
# Tasks

- [x] Mentions & reactions 全体あてのメンションを確認できるようにする。
- [x] Mentions & reactions で、毎日リアクション漏れを確認する。
- [x] 他人の投稿には接触的にリアクションを行う。
- [x] 情報共有他のための投稿を行う。
- [x] タスクの開始時の連絡を行う。
- [x] タスクの終了時に、感想を付けて連絡を行う。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
