### ISSUE TITLE
Chat: Show icon for each message

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#813]
# Tasks

- [x] Show icon for each message
- [x] Show name for each message
- [x] Show time for each message

![Screenshot 2023-05-17 at 13 36 57](https://github.com/sinProject-Inc/talk/assets/70736447/dda43657-5d53-42c1-b840-3b1cbeedc8e3)

---

以前のバージョン
![Screenshot 2023-05-17 at 16 11 25](https://github.com/sinProject-Inc/talk/assets/70736447/12785f4e-906f-47ee-a5f0-8c1c49297fe2)
![Screenshot 2023-05-17 at 16 11 34](https://github.com/sinProject-Inc/talk/assets/70736447/d2a75999-34d8-47ab-a249-69ad39253ecc)

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests

- [x] Implement necessary E2E tests
- [x] Perform functionality checks

---
