### ISSUE TITLE
About hostname

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#880]
# Tasks

- [x] hostnameが取得できるときはあるか？＞確認できなかった
- [x] hostname が取得できるときとできない時があるとのことだが、どのような条件で取得できるか？＞8.8.8.8 は取得できる

新たに、IPv6 アドレスでは、逆引きのエントリがないことが一般的であることがわかった。
以下の対応を追加で行った。

- [x] 利用しないが、非同期処理の参考のため util.primisify を使った非同期処理に変更する。
- [x] client_hostname をログに出力しない。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by sakata0411** [comment]
client_hostname.tsにて直接「8.8.8.8」を指定した際は正常にdns.googleが表示されることを確認できています。
