### ISSUE TITLE
Docs: Update our team policy

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#895]
# Tasks

- [x] 品質向上のため、必要なテストコードを記載します。
- [x] 品質向上のため、手動マージは原則二人以上で行う。
- [x] 工数削減のため、提案内容を実装する前に確認を行う。

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
