### ISSUE TITLE
Docs: Fix creating search_index.json

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#904]
# Tasks

- [x] Docs: Fix creating search_index.json

search_index の再作成を行うと、"path": "slack" が "path": "s\\60-team-sinproject\\30-slack" になりました。
環境：WIndows 10

Macでは問題ないでしょうか？

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
