### ISSUE TITLE
Docs: Policy: Schedule

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#914]
# Tasks

- [ ] Documentation Compliance の下にカテゴリを追加する。

以下を追加

- [ ] 毎週のスケジュールを登録します。
- [ ] チームワークを重視してスケジュール通りに行動します。
- [ ] 予定が変更になる場合には、可能な限り早めに連絡します。

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
