### ISSUE TITLE
About "Prettier Eslint" VSCode Plugin

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#916]
# Tasks

- [ ] 今は Eslint と Prettier の「それぞれ」のプラグインを使っているが「Prettier Eslint」プラグインは使っていない。このプラグインを使う利点はあるか？

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sakata0411** [comment]
自分なりに確認してみた結果を記載します。

・既存の問題である「windows環境で発生しているコミット前に毎回formatをかける必要がある」状況に変化はありませんでした。

・PrettierとESLintのExtensionを両方やめることができるのであれば、Extensionの数を減らせてメリットになったかと思いますが、実際にはPrettierのExtensionと交換する形(ESLintのExtensionは継続して必要)でしたので、この点もメリットとならないように思います。

・他、PrettierとESLintの競合による問題が発生しているのであれば、改善の手助けになるのかもしれませんが、現状そういった問題も発生していない認識なので確認できていません。

以上から、本Extensionを導入する場合は「"Prettier"Extensionと入れ替える」ことになりますが、その入れ替えについてのメリットは見受けられないように思います。
