### ISSUE TITLE
Docs: Make sidebar scrollbar have full height

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#920]
# Tasks

- [ ] sidebarのスクロールバーをheaderの直下まで延長する

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sakata0411** [comment]
調べてみましたが、CSSだけでの実現は厳しそうでした。

typescriptを用いて、「スクロール位置に応じて要素の上部を透明化する」という形で実現はできそうに考えています。
残り調べたい内容としては以下の通りです
- [ ] 背景の透明度をグラデーションするCSS記法(今回はそもそも用いていないので不要ではあります)
　　　→linear-gradient
- [ ] 文字の透明度をグラデーションするCSS記法
　　　→？
- [ ] スクロール位置の取得・処理する方法
　　　→search-modale.svelteで実装しているのでそれを参考に対応可能
- [ ] 上記のCSS記法をtypescriptでコントロールする処理の作成

**Comment by sakata0411** [comment]
実装予定の方法を変更します。

単純にborder・colorを透明にすれば解決するので、以下の形にします。

- [ ] 既存のactive/inactiveとは別のフラグを用意する。(透明化フラグ)
- [ ] 透明化フラグにborder-transparent、text-transparentを設定
- [ ] スクロール表示位置を取得する処理を作成、そこで透明化フラグを操作
　　取得したスクロール位置とchildのscroll_topを比較する処理。
