### ISSUE TITLE
Docs: Fix height of side bar

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#921]
# Tasks

- [ ] sidebarのスクロールバーの位置を検索ボックスとそろえる

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
