### ISSUE TITLE
Show scrollbar like Mac

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#942]
# Tasks

- [ ] Show scrollbar like Mac

https://fractils.vercel.app/#OnMount

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sakata0411** [comment]
貼っていただいていたfractilsでは実現が厳しそうです。

いくつか動作を試してみましたが画面全体サイズのスクロールバーしか生成できず、コードを確認したところ次の記載がありました。

`@note This component only works on viewport-sized elements.`
(MacScrollbar.svelte 12行目)

別のものを探すか、fractilsを参考に独自実装をする必要があるかと思います。

**Comment by sinproject-iwasaki** [comment]
@sakata0411 

かしこまりました。確認ありがとうございます。一旦保留にしておきましょう。
