### ISSUE TITLE
Fix background color of language list on windows

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#959]
# Tasks

- [ ] windows環境において、言語選択のプルダウンリストが見づらくなっているため背景色を設定する
![スクリーンショット (1)](https://github.com/sinProject-Inc/talk/assets/130205200/7897d016-6c19-4904-8c9d-de87cb4d4ef3)![スクリーンショット (2)](https://github.com/sinProject-Inc/talk/assets/130205200/72bd4328-f0f0-4243-ae1d-0bfa7fd6b9e0)

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sakata0411** [comment]
選択肢が表示される部分の背景色は現状<select>に依存しています。
そのため、translate画面とそれ以外とで見た目に差が発生しています。(class:glass-buttonの有無)

chatGPTに聞いてみたところ<select>の子<option>に対して直接bg-color指定ができるみたいですが、
現状のソースコードでは<select>にelementをbing:thisする形で実装しているため、コード上<options>が見えていません。

どうやってこの子要素に直接bg-colorを指定するのか、その方法を調べる必要がある状態です。

また、その際windowsのときのみ処理を行うようにするのか、macも含めてすべてにおいて適応する形とするのかも確認が必要と思われます。

**Comment by sinproject-iwasaki** [comment]
@sakata0411 

調査ありがとございました。
カラーテーマとフォントカラーの対応の問題の可能性がありそうです。
対応方法はこちらでも検討してみたいと思いますので、一旦保留にしておきましょう。

**Comment by sakata0411** [comment]
theme対応により状況が変わる可能性が高いので、まずはそちらの対応を待ってから再度確認する。
#607

**Comment by sakata0411** [comment]
theme対応により、文字が読める状態にはなりました。

ただし、main/chat画面とtranslate画面との間で背景色が違う状況は継続中で、
新たにmain/chat画面の方は「ボタン側のhover:bgが選択肢にも影響される」状態を確認できました。

![959-main_chat_dark](https://github.com/sinProject-Inc/talk/assets/130205200/216ac2e7-7962-45ac-b607-aec613596790)
![959-main_chat_dark_onmouse](https://github.com/sinProject-Inc/talk/assets/130205200/8eea66fb-6230-4a13-96d7-88f6074d818a)
