### ISSUE TITLE
Add sound volume control bar

### ISSUE THREAD

**Issue by sakata0411** [sinProject-Inc/talk#970]
# Tasks

各読み上げボイスやDocs画面のページ遷移交換等の音量について、現状ではユーザーがブラウザ自体or本体の音量を調節する必要があるため、手軽に調節できるように音量調節バーを追加したらUX向上に繋がるのではないかと思います。

- [ ] 音量調節機能の実装

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
