### ISSUE TITLE
Docs: Search box animation

### ISSUE THREAD

**Issue by milkyskies** [sinProject-Inc/talk#986]
# Tasks
https://youtu.be/YalEnQ-SKa0?t=311
or same as left bar
- [x] サーチボックスを開く際の挙動は変更しない。> 早くアニメーションする。
- [x] 閉じる際の挙動をmobile-side-barを参考にアニメーションをつける。
　　(同じぐらいの速度で消える様にし、背景のぼかしもじわじわ変わるようにする)

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
